window.STOCK_DASHBOARD_DATA = {
  "generated_at": "2026-06-05 21:26:26",
  "strategies": {
    "adaptive": {
      "key": "adaptive",
      "label": "自适应策略",
      "source_file": "adaptive://derived",
      "available_dates": [
        "2026-06-08",
        "2026-06-05",
        "2026-06-04",
        "2026-06-03",
        "2026-06-02",
        "2026-06-01",
        "2026-05-29",
        "2026-05-28",
        "2026-05-27",
        "2026-05-26",
        "2026-05-25",
        "2026-05-22",
        "2026-05-21",
        "2026-05-20",
        "2026-05-19",
        "2026-05-18",
        "2026-05-15",
        "2026-05-14",
        "2026-05-13",
        "2026-05-12",
        "2026-05-11",
        "2026-05-08",
        "2026-05-07",
        "2026-05-06",
        "2026-04-30",
        "2026-04-29",
        "2026-04-28",
        "2026-04-27",
        "2026-04-24",
        "2026-04-23",
        "2026-04-22",
        "2026-04-21",
        "2026-04-20",
        "2026-04-17",
        "2026-04-16",
        "2026-04-15",
        "2026-04-14",
        "2026-04-13",
        "2026-04-10",
        "2026-04-09",
        "2026-04-08",
        "2026-04-07",
        "2026-04-03",
        "2026-04-02",
        "2026-04-01",
        "2026-03-31",
        "2026-03-30",
        "2026-03-27",
        "2026-03-26",
        "2026-03-25",
        "2026-03-24",
        "2026-03-23",
        "2026-03-20",
        "2026-03-19",
        "2026-03-18",
        "2026-03-17",
        "2026-03-16",
        "2026-03-13",
        "2026-03-12",
        "2026-03-11",
        "2026-03-10",
        "2026-03-09",
        "2026-03-06",
        "2026-03-05",
        "2026-03-04",
        "2026-03-03",
        "2026-03-02",
        "2026-02-27",
        "2026-02-26",
        "2026-02-25"
      ],
      "latest_run_time": "2026-05-28 09:29:16",
      "records": [
        {
          "run_time": "2026-05-26 20:03:05",
          "trade_date": "2026-05-27",
          "symbol": "605077",
          "name": "华康股份",
          "threshold_mode": "normal",
          "score_total": 70.46,
          "close": 18.29,
          "stop_loss_price": 16.88,
          "take_profit_price": 21.1,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-25 20:07:08",
          "trade_date": "2026-05-26",
          "symbol": "603266",
          "name": "天龙股份",
          "threshold_mode": "normal",
          "score_total": 72.05,
          "close": 20.55,
          "stop_loss_price": 19.57,
          "take_profit_price": 22.5,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-22 19:38:36",
          "trade_date": "2026-05-25",
          "symbol": "603197",
          "name": "保隆科技",
          "threshold_mode": "normal",
          "score_total": 69.52,
          "close": 34.73,
          "stop_loss_price": 33.32,
          "take_profit_price": 37.54,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-21 19:53:14",
          "trade_date": "2026-05-22",
          "symbol": "000333",
          "name": "美的集团",
          "threshold_mode": "normal",
          "score_total": 71.45,
          "close": 81.5,
          "stop_loss_price": 78.79,
          "take_profit_price": 86.91,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-20 19:37:56",
          "trade_date": "2026-05-21",
          "symbol": "601330",
          "name": "绿色动力",
          "threshold_mode": "normal",
          "score_total": 68.88,
          "close": 9.04,
          "stop_loss_price": 8.31,
          "take_profit_price": 10.49,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-19 20:04:39",
          "trade_date": "2026-05-20",
          "symbol": "603197",
          "name": "保隆科技",
          "threshold_mode": "normal",
          "score_total": 69.9,
          "close": 34.64,
          "stop_loss_price": 33.41,
          "take_profit_price": 37.09,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-18 22:28:54",
          "trade_date": "2026-05-19",
          "symbol": "600642",
          "name": "申能股份",
          "threshold_mode": "normal",
          "score_total": 69.27,
          "close": 9.41,
          "stop_loss_price": 8.94,
          "take_profit_price": 10.33,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-15 20:07:01",
          "trade_date": "2026-05-18",
          "symbol": "603126",
          "name": "中材节能",
          "threshold_mode": "normal",
          "score_total": 71.03,
          "close": 8.5,
          "stop_loss_price": 7.83,
          "take_profit_price": 9.82,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-14 19:34:46",
          "trade_date": "2026-05-15",
          "symbol": "000652",
          "name": "泰达股份",
          "threshold_mode": "normal",
          "score_total": 72.37,
          "close": 4.29,
          "stop_loss_price": 4.1,
          "take_profit_price": 4.65,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-13 20:04:08",
          "trade_date": "2026-05-14",
          "symbol": "603339",
          "name": "四方科技",
          "threshold_mode": "normal",
          "score_total": 72.61,
          "close": 13.81,
          "stop_loss_price": 13.3,
          "take_profit_price": 14.82,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-12 21:23:48",
          "trade_date": "2026-05-13",
          "symbol": "001324",
          "name": "长青科技",
          "threshold_mode": "normal",
          "score_total": 72.31,
          "close": 20.6,
          "stop_loss_price": 19.56,
          "take_profit_price": 22.66,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-11 20:09:13",
          "trade_date": "2026-05-12",
          "symbol": "000766",
          "name": "通化金马",
          "threshold_mode": "normal",
          "score_total": 73.94,
          "close": 23.63,
          "stop_loss_price": 21.83,
          "take_profit_price": 27.21,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-08 21:34:05",
          "trade_date": "2026-05-11",
          "symbol": "600007",
          "name": "中国国贸",
          "threshold_mode": "normal",
          "score_total": 70.38,
          "close": 21.7,
          "stop_loss_price": 20.98,
          "take_profit_price": 23.12,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-07 20:54:00",
          "trade_date": "2026-05-08",
          "symbol": "600007",
          "name": "中国国贸",
          "threshold_mode": "normal",
          "score_total": 69.07,
          "close": 21.6,
          "stop_loss_price": 20.88,
          "take_profit_price": 23.02,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-06 20:04:29",
          "trade_date": "2026-05-07",
          "symbol": "002831",
          "name": "裕同科技",
          "threshold_mode": "normal",
          "score_total": 71.84,
          "close": 37.55,
          "stop_loss_price": 35.01,
          "take_profit_price": 42.61,
          "suggested_holding_days": 5,
          "exit_plan": "默认持有5天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-30 20:27:15",
          "trade_date": "2026-05-06",
          "symbol": "605268",
          "name": "王力安防",
          "threshold_mode": "normal",
          "score_total": 69.13,
          "close": 12.98,
          "stop_loss_price": 12.06,
          "take_profit_price": 14.81,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-29 20:02:33",
          "trade_date": "2026-04-30",
          "symbol": "601998",
          "name": "中信银行",
          "threshold_mode": "normal",
          "score_total": 74.78,
          "close": 8.4,
          "stop_loss_price": 8.13,
          "take_profit_price": 8.93,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-28 20:08:42",
          "trade_date": "2026-04-29",
          "symbol": "000550",
          "name": "江铃汽车",
          "threshold_mode": "normal",
          "score_total": 70.61,
          "close": 19.02,
          "stop_loss_price": 18.1,
          "take_profit_price": 20.85,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-27 20:17:59",
          "trade_date": "2026-04-28",
          "symbol": "605319",
          "name": "无锡振华",
          "threshold_mode": "normal",
          "score_total": 71.21,
          "close": 27.55,
          "stop_loss_price": 25.45,
          "take_profit_price": 31.74,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-25 11:29:13",
          "trade_date": "2026-04-27",
          "symbol": "600007",
          "name": "中国国贸",
          "threshold_mode": "normal",
          "score_total": 69.36,
          "close": 21.53,
          "stop_loss_price": 20.92,
          "take_profit_price": 22.73,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-23 19:39:53",
          "trade_date": "2026-04-24",
          "symbol": "601998",
          "name": "中信银行",
          "threshold_mode": "normal",
          "score_total": 69.78,
          "close": 8.37,
          "stop_loss_price": 8.1,
          "take_profit_price": 8.89,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-22 21:22:30",
          "trade_date": "2026-04-23",
          "symbol": "603345",
          "name": "安井食品",
          "threshold_mode": "normal",
          "score_total": 70.05,
          "close": 94.6,
          "stop_loss_price": 89.96,
          "take_profit_price": 103.86,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-21 20:14:48",
          "trade_date": "2026-04-22",
          "symbol": "601998",
          "name": "中信银行",
          "threshold_mode": "normal",
          "score_total": 66.59,
          "close": 8.44,
          "stop_loss_price": 8.17,
          "take_profit_price": 8.97,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-20 21:06:03",
          "trade_date": "2026-04-21",
          "symbol": "601825",
          "name": "沪农商行",
          "threshold_mode": "normal",
          "score_total": 68.3,
          "close": 9.14,
          "stop_loss_price": 8.85,
          "take_profit_price": 9.71,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-18 19:22:50",
          "trade_date": "2026-04-20",
          "symbol": "002653",
          "name": "海思科",
          "threshold_mode": "normal",
          "score_total": 68.4,
          "close": 56.02,
          "stop_loss_price": 50.8,
          "take_profit_price": 66.45,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-16 19:56:36",
          "trade_date": "2026-04-17",
          "symbol": "601077",
          "name": "渝农商行",
          "threshold_mode": "normal",
          "score_total": 67.09,
          "close": 7.21,
          "stop_loss_price": 6.94,
          "take_profit_price": 7.73,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-15 19:30:53",
          "trade_date": "2026-04-16",
          "symbol": "002648",
          "name": "卫星化学",
          "threshold_mode": "normal",
          "score_total": 66.59,
          "close": 27.92,
          "stop_loss_price": 25.62,
          "take_profit_price": 32.51,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-14 22:55:38",
          "trade_date": "2026-04-15",
          "symbol": "600015",
          "name": "华夏银行",
          "threshold_mode": "normal",
          "score_total": 66.56,
          "close": 7.31,
          "stop_loss_price": 7.11,
          "take_profit_price": 7.7,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-13 23:03:44",
          "trade_date": "2026-04-14",
          "symbol": "600429",
          "name": "三元股份",
          "threshold_mode": "normal",
          "score_total": 60.92,
          "close": 6.0,
          "stop_loss_price": 5.67,
          "take_profit_price": 6.65,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-11 09:54:03",
          "trade_date": "2026-04-13",
          "symbol": "002032",
          "name": "苏 泊 尔",
          "threshold_mode": "normal",
          "score_total": 68.32,
          "close": 45.28,
          "stop_loss_price": 43.85,
          "take_profit_price": 48.12,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-09 20:01:34",
          "trade_date": "2026-04-10",
          "symbol": "600015",
          "name": "华夏银行",
          "threshold_mode": "normal",
          "score_total": 69.01,
          "close": 7.32,
          "stop_loss_price": 7.08,
          "take_profit_price": 7.78,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-08 20:08:02",
          "trade_date": "2026-04-09",
          "symbol": "600750",
          "name": "华润江中",
          "threshold_mode": "normal",
          "score_total": 66.62,
          "close": 26.35,
          "stop_loss_price": 25.1,
          "take_profit_price": 28.84,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-07 20:07:32",
          "trade_date": "2026-04-08",
          "symbol": "601825",
          "name": "沪农商行",
          "threshold_mode": "normal",
          "score_total": 67.47,
          "close": 9.03,
          "stop_loss_price": 8.74,
          "take_profit_price": 9.6,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-06 20:42:19",
          "trade_date": "2026-04-07",
          "symbol": "601939",
          "name": "建设银行",
          "threshold_mode": "normal",
          "score_total": 70.29,
          "close": 9.4,
          "stop_loss_price": 9.1,
          "take_profit_price": 9.98,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-02 20:17:10",
          "trade_date": "2026-04-03",
          "symbol": "600919",
          "name": "江苏银行",
          "threshold_mode": "normal",
          "score_total": 68.49,
          "close": 10.88,
          "stop_loss_price": 10.56,
          "take_profit_price": 11.51,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-04-01 21:50:30",
          "trade_date": "2026-04-02",
          "symbol": "600919",
          "name": "江苏银行",
          "threshold_mode": "normal",
          "score_total": 68.97,
          "close": 10.82,
          "stop_loss_price": 10.49,
          "take_profit_price": 11.47,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-31 21:15:40",
          "trade_date": "2026-04-01",
          "symbol": "600719",
          "name": "大连热电",
          "threshold_mode": "normal",
          "score_total": 69.8,
          "close": 6.96,
          "stop_loss_price": 6.32,
          "take_profit_price": 8.22,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-30 20:52:47",
          "trade_date": "2026-03-31",
          "symbol": "600575",
          "name": "淮河能源",
          "threshold_mode": "normal",
          "score_total": 70.8,
          "close": 4.0,
          "stop_loss_price": 3.76,
          "take_profit_price": 4.46,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-30 08:48:59",
          "trade_date": "2026-03-30",
          "symbol": "001289",
          "name": "龙源电力",
          "threshold_mode": "normal",
          "score_total": 73.79,
          "close": 18.29,
          "stop_loss_price": 17.27,
          "take_profit_price": 20.32,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-26 20:45:46",
          "trade_date": "2026-03-27",
          "symbol": "600025",
          "name": "华能水电",
          "threshold_mode": "normal",
          "score_total": 71.87,
          "close": 10.27,
          "stop_loss_price": 9.92,
          "take_profit_price": 10.95,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-25 20:19:07",
          "trade_date": "2026-03-26",
          "symbol": "600025",
          "name": "华能水电",
          "threshold_mode": "normal",
          "score_total": 74.98,
          "close": 10.23,
          "stop_loss_price": 9.87,
          "take_profit_price": 10.93,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-24 20:03:54",
          "trade_date": "2026-03-25",
          "symbol": "600925",
          "name": "苏能股份",
          "threshold_mode": "normal",
          "score_total": 72.15,
          "close": 4.88,
          "stop_loss_price": 4.7,
          "take_profit_price": 5.22,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-23 11:29:44",
          "trade_date": "2026-03-23",
          "symbol": "002856",
          "name": "美芝股份",
          "threshold_mode": "normal",
          "score_total": 81.42,
          "close": 11.24,
          "stop_loss_price": 10.56,
          "take_profit_price": 12.13,
          "suggested_holding_days": 4,
          "exit_plan": "",
          "source_strategy": "recommend-oversold"
        },
        {
          "run_time": "2026-03-23 11:29:44",
          "trade_date": "2026-03-23",
          "symbol": "603179",
          "name": "新泉股份",
          "threshold_mode": "normal",
          "score_total": 80.84,
          "close": 64.0,
          "stop_loss_price": 60.16,
          "take_profit_price": 69.12,
          "suggested_holding_days": 4,
          "exit_plan": "",
          "source_strategy": "recommend-oversold"
        },
        {
          "run_time": "2026-03-23 11:29:44",
          "trade_date": "2026-03-23",
          "symbol": "002442",
          "name": "龙星科技",
          "threshold_mode": "normal",
          "score_total": 76.58,
          "close": 5.73,
          "stop_loss_price": 5.38,
          "take_profit_price": 6.18,
          "suggested_holding_days": 4,
          "exit_plan": "",
          "source_strategy": "recommend-oversold"
        }
      ],
      "date_summaries": {
        "2026-03-24": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "chosen_count": null,
          "formal_action": "cash",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-03-25": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-03-26": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-03-27": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-03-30": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-03-31": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-01": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-02": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-03": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-07": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-08": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-09": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-10": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-13": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-14": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-15": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-16": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-17": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-20": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-21": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-22": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-23": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-24": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-27": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-28": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-29": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-04-30": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-06": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-07": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-08": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-11": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-12": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-13": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-14": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-15": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-18": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-19": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-20": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-21": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-22": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-25": {
          "market_state": "neutral",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-26": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-27": {
          "market_state": "bull",
          "tried_strategies": [
            "recommend-pullback"
          ],
          "chosen_strategy": "recommend-pullback",
          "has_recommendations": true,
          "chosen_count": 1,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-05-28": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": "cash",
          "has_recommendations": false,
          "chosen_count": 0,
          "formal_action": "cash",
          "opportunity_count": 3,
          "has_observation_candidates": true
        },
        "2026-05-29": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": "cash",
          "has_recommendations": false,
          "chosen_count": 0,
          "formal_action": "cash",
          "opportunity_count": 4,
          "has_observation_candidates": true
        },
        "2026-06-01": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": "cash",
          "has_recommendations": false,
          "chosen_count": 0,
          "formal_action": "cash",
          "opportunity_count": 4,
          "has_observation_candidates": true
        },
        "2026-06-02": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": "cash",
          "has_recommendations": false,
          "chosen_count": 0,
          "formal_action": "cash",
          "opportunity_count": 4,
          "has_observation_candidates": true
        },
        "2026-06-03": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": "cash",
          "has_recommendations": false,
          "chosen_count": 0,
          "formal_action": "cash",
          "opportunity_count": 4,
          "has_observation_candidates": true
        },
        "2026-06-04": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": "cash",
          "has_recommendations": false,
          "chosen_count": 0,
          "formal_action": "cash",
          "opportunity_count": 4,
          "has_observation_candidates": true
        },
        "2026-06-05": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": "cash",
          "has_recommendations": false,
          "chosen_count": 0,
          "formal_action": "cash",
          "opportunity_count": 4,
          "has_observation_candidates": true
        },
        "2026-06-08": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": "cash",
          "has_recommendations": false,
          "chosen_count": 0,
          "formal_action": "cash",
          "opportunity_count": 4,
          "has_observation_candidates": true
        },
        "2026-03-23": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": "recommend-oversold",
          "has_recommendations": true,
          "formal_action": "trade",
          "opportunity_count": 0,
          "has_observation_candidates": false
        },
        "2026-03-20": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 6,
          "has_observation_candidates": true
        },
        "2026-03-19": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 6,
          "has_observation_candidates": true
        },
        "2026-03-18": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 6,
          "has_observation_candidates": true
        },
        "2026-03-17": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 6,
          "has_observation_candidates": true
        },
        "2026-03-16": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 6,
          "has_observation_candidates": true
        },
        "2026-03-13": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 6,
          "has_observation_candidates": true
        },
        "2026-03-12": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 3,
          "has_observation_candidates": true
        },
        "2026-03-11": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 3,
          "has_observation_candidates": true
        },
        "2026-03-10": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 5,
          "has_observation_candidates": true
        },
        "2026-03-09": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 3,
          "has_observation_candidates": true
        },
        "2026-03-06": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 3,
          "has_observation_candidates": true
        },
        "2026-03-05": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 6,
          "has_observation_candidates": true
        },
        "2026-03-04": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 6,
          "has_observation_candidates": true
        },
        "2026-03-03": {
          "market_state": "bear",
          "tried_strategies": [
            "recommend-oversold",
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 3,
          "has_observation_candidates": true
        },
        "2026-03-02": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 3,
          "has_observation_candidates": true
        },
        "2026-02-27": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 1,
          "has_observation_candidates": true
        },
        "2026-02-26": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 1,
          "has_observation_candidates": true
        },
        "2026-02-25": {
          "market_state": "neutral",
          "tried_strategies": [
            "cash"
          ],
          "chosen_strategy": null,
          "has_recommendations": false,
          "formal_action": "cash",
          "opportunity_count": 2,
          "has_observation_candidates": true
        }
      }
    },
    "opportunity": {
      "key": "opportunity",
      "label": "机会池",
      "source_file": "reports/opportunity_recommendations.csv",
      "available_dates": [
        "2026-06-08",
        "2026-06-05",
        "2026-06-04",
        "2026-06-03",
        "2026-06-02",
        "2026-06-01",
        "2026-05-29",
        "2026-05-28",
        "2026-03-20",
        "2026-03-19",
        "2026-03-18",
        "2026-03-17",
        "2026-03-16",
        "2026-03-13",
        "2026-03-12",
        "2026-03-11",
        "2026-03-10",
        "2026-03-09",
        "2026-03-06",
        "2026-03-05",
        "2026-03-04",
        "2026-03-03",
        "2026-03-02",
        "2026-02-27",
        "2026-02-26",
        "2026-02-25"
      ],
      "latest_run_time": "2026-06-05 21:26:26",
      "records": [
        {
          "run_time": "2026-06-05 21:26:26",
          "trade_date": "2026-06-08",
          "symbol": "002815",
          "name": "崇达技术",
          "threshold_mode": "normal",
          "score_total": 76.8,
          "close": 17.77,
          "stop_loss_price": 16.27,
          "take_profit_price": 20.75,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-06-05 21:26:26",
          "trade_date": "2026-06-08",
          "symbol": "001326",
          "name": "联域股份",
          "threshold_mode": "normal",
          "score_total": 73.9,
          "close": 69.48,
          "stop_loss_price": 62.4,
          "take_profit_price": 83.63,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-06-05 21:26:26",
          "trade_date": "2026-06-08",
          "symbol": "600546",
          "name": "山煤国际",
          "threshold_mode": "normal",
          "score_total": 67.35,
          "close": 14.11,
          "stop_loss_price": 12.96,
          "take_profit_price": 16.39,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-06-05 21:26:26",
          "trade_date": "2026-06-08",
          "symbol": "600008",
          "name": "首创环保",
          "threshold_mode": "normal",
          "score_total": 66.53,
          "close": 3.14,
          "stop_loss_price": 3.03,
          "take_profit_price": 3.35,
          "suggested_holding_days": 1,
          "exit_plan": "默认持有1天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-06-04 19:55:56",
          "trade_date": "2026-06-05",
          "symbol": "600483",
          "name": "福能股份",
          "threshold_mode": "normal",
          "score_total": 75.5,
          "close": 11.92,
          "stop_loss_price": 11.17,
          "take_profit_price": 13.4,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-06-04 19:55:56",
          "trade_date": "2026-06-05",
          "symbol": "003043",
          "name": "华亚智能",
          "threshold_mode": "normal",
          "score_total": 74.92,
          "close": 67.57,
          "stop_loss_price": 61.27,
          "take_profit_price": 80.17,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-06-04 19:55:56",
          "trade_date": "2026-06-05",
          "symbol": "600012",
          "name": "皖通高速",
          "threshold_mode": "normal",
          "score_total": 71.16,
          "close": 16.45,
          "stop_loss_price": 15.55,
          "take_profit_price": 18.24,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-06-04 19:55:56",
          "trade_date": "2026-06-05",
          "symbol": "603099",
          "name": "长白山",
          "threshold_mode": "normal",
          "score_total": 69.75,
          "close": 38.04,
          "stop_loss_price": 35.83,
          "take_profit_price": 42.45,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-06-03 20:02:24",
          "trade_date": "2026-06-04",
          "symbol": "603386",
          "name": "骏亚科技",
          "threshold_mode": "normal",
          "score_total": 73.73,
          "close": 17.04,
          "stop_loss_price": 15.57,
          "take_profit_price": 19.96,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-06-03 20:02:24",
          "trade_date": "2026-06-04",
          "symbol": "600222",
          "name": "太龙药业",
          "threshold_mode": "normal",
          "score_total": 73.29,
          "close": 8.38,
          "stop_loss_price": 7.78,
          "take_profit_price": 9.57,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-06-03 20:02:24",
          "trade_date": "2026-06-04",
          "symbol": "002768",
          "name": "国恩股份",
          "threshold_mode": "normal",
          "score_total": 70.52,
          "close": 63.6,
          "stop_loss_price": 58.12,
          "take_profit_price": 74.55,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-06-03 20:02:24",
          "trade_date": "2026-06-04",
          "symbol": "600919",
          "name": "江苏银行",
          "threshold_mode": "normal",
          "score_total": 66.86,
          "close": 11.32,
          "stop_loss_price": 10.99,
          "take_profit_price": 11.97,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-06-02 20:17:29",
          "trade_date": "2026-06-03",
          "symbol": "600642",
          "name": "申能股份",
          "threshold_mode": "normal",
          "score_total": 75.96,
          "close": 10.65,
          "stop_loss_price": 10.02,
          "take_profit_price": 11.91,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-06-02 20:17:29",
          "trade_date": "2026-06-03",
          "symbol": "000582",
          "name": "北部湾港",
          "threshold_mode": "normal",
          "score_total": 74.19,
          "close": 14.05,
          "stop_loss_price": 12.93,
          "take_profit_price": 16.27,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-06-02 20:17:29",
          "trade_date": "2026-06-03",
          "symbol": "002406",
          "name": "远东传动",
          "threshold_mode": "normal",
          "score_total": 69.52,
          "close": 8.41,
          "stop_loss_price": 7.76,
          "take_profit_price": 9.7,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-06-02 20:17:29",
          "trade_date": "2026-06-03",
          "symbol": "600018",
          "name": "上港集团",
          "threshold_mode": "normal",
          "score_total": 67.23,
          "close": 5.14,
          "stop_loss_price": 5.02,
          "take_profit_price": 5.36,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-06-01 19:58:54",
          "trade_date": "2026-06-02",
          "symbol": "002669",
          "name": "康达新材",
          "threshold_mode": "normal",
          "score_total": 75.87,
          "close": 15.91,
          "stop_loss_price": 14.08,
          "take_profit_price": 19.55,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-06-01 19:58:54",
          "trade_date": "2026-06-02",
          "symbol": "600207",
          "name": "安彩高科",
          "threshold_mode": "normal",
          "score_total": 73.84,
          "close": 7.27,
          "stop_loss_price": 6.49,
          "take_profit_price": 8.81,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-06-01 19:58:54",
          "trade_date": "2026-06-02",
          "symbol": "001965",
          "name": "招商公路",
          "threshold_mode": "normal",
          "score_total": 70.65,
          "close": 9.98,
          "stop_loss_price": 9.62,
          "take_profit_price": 10.68,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-06-01 19:58:54",
          "trade_date": "2026-06-02",
          "symbol": "600203",
          "name": "福日电子",
          "threshold_mode": "normal",
          "score_total": 69.64,
          "close": 13.06,
          "stop_loss_price": 12.15,
          "take_profit_price": 14.86,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-31 19:20:08",
          "trade_date": "2026-06-01",
          "symbol": "600460",
          "name": "士兰微",
          "threshold_mode": "normal",
          "score_total": 78.26,
          "close": 34.6,
          "stop_loss_price": 31.38,
          "take_profit_price": 41.02,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-05-31 19:20:08",
          "trade_date": "2026-06-01",
          "symbol": "000582",
          "name": "北部湾港",
          "threshold_mode": "normal",
          "score_total": 77.37,
          "close": 13.57,
          "stop_loss_price": 12.55,
          "take_profit_price": 15.61,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-05-31 19:20:08",
          "trade_date": "2026-06-01",
          "symbol": "601059",
          "name": "信达证券",
          "threshold_mode": "normal",
          "score_total": 70.19,
          "close": 17.2,
          "stop_loss_price": 16.79,
          "take_profit_price": 18.01,
          "suggested_holding_days": 2,
          "exit_plan": "默认持有2天；买后不强就退出；跌回MA20下方或单笔亏损4%到5%止损。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-31 19:20:08",
          "trade_date": "2026-06-01",
          "symbol": "600018",
          "name": "上港集团",
          "threshold_mode": "normal",
          "score_total": 69.6,
          "close": 5.13,
          "stop_loss_price": 5.02,
          "take_profit_price": 5.34,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-28 20:14:50",
          "trade_date": "2026-05-29",
          "symbol": "002079",
          "name": "苏州固锝",
          "threshold_mode": "normal",
          "score_total": 77.81,
          "close": 13.3,
          "stop_loss_price": 12.39,
          "take_profit_price": 15.11,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-05-28 20:14:50",
          "trade_date": "2026-05-29",
          "symbol": "603725",
          "name": "天安新材",
          "threshold_mode": "normal",
          "score_total": 76.15,
          "close": 11.74,
          "stop_loss_price": 10.62,
          "take_profit_price": 13.97,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-relative"
        },
        {
          "run_time": "2026-05-28 20:14:50",
          "trade_date": "2026-05-29",
          "symbol": "605500",
          "name": "森林包装",
          "threshold_mode": "normal",
          "score_total": 73.33,
          "close": 9.89,
          "stop_loss_price": 8.85,
          "take_profit_price": 11.96,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-28 20:14:50",
          "trade_date": "2026-05-29",
          "symbol": "603666",
          "name": "亿嘉和",
          "threshold_mode": "normal",
          "score_total": 71.94,
          "close": 30.78,
          "stop_loss_price": 28.84,
          "take_profit_price": 34.65,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-05-28 09:29:15",
          "trade_date": "2026-05-28",
          "symbol": "603725",
          "name": "天安新材",
          "threshold_mode": "normal",
          "score_total": 91.58,
          "close": 12.2,
          "stop_loss_price": 11.12,
          "take_profit_price": 14.34,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-05-28 09:29:15",
          "trade_date": "2026-05-28",
          "symbol": "600226",
          "name": "亨通股份",
          "threshold_mode": "normal",
          "score_total": 89.79,
          "close": 6.63,
          "stop_loss_price": 6.16,
          "take_profit_price": 7.56,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-05-28 09:29:16",
          "trade_date": "2026-05-28",
          "symbol": "003019",
          "name": "宸展光电",
          "threshold_mode": "normal",
          "score_total": 88.72,
          "close": 44.17,
          "stop_loss_price": 40.74,
          "take_profit_price": 51.01,
          "suggested_holding_days": 3,
          "exit_plan": "默认持有3天；买后1到2天不强或跌回MA20附近转弱就退出；放量冲高回落可分批止盈。",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-19 20:41:23",
          "trade_date": "2026-03-20",
          "symbol": "600307",
          "name": "酒钢宏兴",
          "threshold_mode": "normal",
          "score_total": 88.22,
          "close": 2.28,
          "stop_loss_price": 2.07,
          "take_profit_price": 2.69,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-19 20:41:23",
          "trade_date": "2026-03-20",
          "symbol": "603175",
          "name": "超颖电子",
          "threshold_mode": "normal",
          "score_total": 86.02,
          "close": 91.65,
          "stop_loss_price": 82.37,
          "take_profit_price": 110.2,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-19 20:41:23",
          "trade_date": "2026-03-20",
          "symbol": "603421",
          "name": "鼎信通讯",
          "threshold_mode": "normal",
          "score_total": 84.95,
          "close": 10.33,
          "stop_loss_price": 9.31,
          "take_profit_price": 12.36,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-19 21:51:54",
          "trade_date": "2026-03-20",
          "symbol": "600132",
          "name": "重庆啤酒",
          "threshold_mode": "normal",
          "score_total": 72.18,
          "close": 56.93,
          "stop_loss_price": 54.6,
          "take_profit_price": 61.58,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-19 21:51:54",
          "trade_date": "2026-03-20",
          "symbol": "603050",
          "name": "科林电气",
          "threshold_mode": "normal",
          "score_total": 72.06,
          "close": 22.86,
          "stop_loss_price": 20.71,
          "take_profit_price": 27.15,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-19 21:51:54",
          "trade_date": "2026-03-20",
          "symbol": "603565",
          "name": "中谷物流",
          "threshold_mode": "normal",
          "score_total": 70.39,
          "close": 11.01,
          "stop_loss_price": 10.64,
          "take_profit_price": 11.74,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-18 21:15:08",
          "trade_date": "2026-03-19",
          "symbol": "601218",
          "name": "吉鑫科技",
          "threshold_mode": "normal",
          "score_total": 92.95,
          "close": 6.75,
          "stop_loss_price": 6.16,
          "take_profit_price": 7.91,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-18 21:15:08",
          "trade_date": "2026-03-19",
          "symbol": "600691",
          "name": "潞化科技",
          "threshold_mode": "normal",
          "score_total": 89.85,
          "close": 4.42,
          "stop_loss_price": 3.89,
          "take_profit_price": 5.46,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-18 21:15:08",
          "trade_date": "2026-03-19",
          "symbol": "603538",
          "name": "美诺华",
          "threshold_mode": "normal",
          "score_total": 89.81,
          "close": 26.36,
          "stop_loss_price": 24.46,
          "take_profit_price": 30.15,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-18 22:22:38",
          "trade_date": "2026-03-19",
          "symbol": "600935",
          "name": "华塑股份",
          "threshold_mode": "normal",
          "score_total": 73.74,
          "close": 3.0,
          "stop_loss_price": 2.75,
          "take_profit_price": 3.49,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-18 22:22:38",
          "trade_date": "2026-03-19",
          "symbol": "601001",
          "name": "晋控煤业",
          "threshold_mode": "normal",
          "score_total": 71.59,
          "close": 17.21,
          "stop_loss_price": 15.71,
          "take_profit_price": 20.19,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-18 22:22:38",
          "trade_date": "2026-03-19",
          "symbol": "605011",
          "name": "杭州热电",
          "threshold_mode": "normal",
          "score_total": 71.4,
          "close": 21.3,
          "stop_loss_price": 20.47,
          "take_profit_price": 22.94,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-17 21:58:59",
          "trade_date": "2026-03-18",
          "symbol": "603538",
          "name": "美诺华",
          "threshold_mode": "normal",
          "score_total": 90.9,
          "close": 26.36,
          "stop_loss_price": 24.58,
          "take_profit_price": 29.91,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-17 21:58:59",
          "trade_date": "2026-03-18",
          "symbol": "000912",
          "name": "泸天化",
          "threshold_mode": "normal",
          "score_total": 90.13,
          "close": 6.47,
          "stop_loss_price": 5.7,
          "take_profit_price": 7.99,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-17 21:58:59",
          "trade_date": "2026-03-18",
          "symbol": "600844",
          "name": "金煤科技",
          "threshold_mode": "normal",
          "score_total": 89.62,
          "close": 3.99,
          "stop_loss_price": 3.53,
          "take_profit_price": 4.89,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-17 22:09:38",
          "trade_date": "2026-03-18",
          "symbol": "000539",
          "name": "粤电力Ａ",
          "threshold_mode": "normal",
          "score_total": 71.18,
          "close": 5.1,
          "stop_loss_price": 4.84,
          "take_profit_price": 5.6,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-17 22:09:38",
          "trade_date": "2026-03-18",
          "symbol": "000966",
          "name": "长源电力",
          "threshold_mode": "normal",
          "score_total": 70.87,
          "close": 4.81,
          "stop_loss_price": 4.52,
          "take_profit_price": 5.37,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-17 22:09:38",
          "trade_date": "2026-03-18",
          "symbol": "001207",
          "name": "联科科技",
          "threshold_mode": "normal",
          "score_total": 70.82,
          "close": 28.47,
          "stop_loss_price": 26.3,
          "take_profit_price": 32.79,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-16 19:58:49",
          "trade_date": "2026-03-17",
          "symbol": "000537",
          "name": "绿发电力",
          "threshold_mode": "normal",
          "score_total": 91.72,
          "close": 11.23,
          "stop_loss_price": 10.33,
          "take_profit_price": 13.02,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-16 19:58:49",
          "trade_date": "2026-03-17",
          "symbol": "600746",
          "name": "江苏索普",
          "threshold_mode": "normal",
          "score_total": 90.01,
          "close": 9.16,
          "stop_loss_price": 8.51,
          "take_profit_price": 10.44,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-16 19:58:49",
          "trade_date": "2026-03-17",
          "symbol": "603421",
          "name": "鼎信通讯",
          "threshold_mode": "normal",
          "score_total": 89.65,
          "close": 10.32,
          "stop_loss_price": 9.49,
          "take_profit_price": 11.96,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-16 20:57:16",
          "trade_date": "2026-03-17",
          "symbol": "600528",
          "name": "中铁工业",
          "threshold_mode": "normal",
          "score_total": 73.53,
          "close": 8.51,
          "stop_loss_price": 8.23,
          "take_profit_price": 9.06,
          "suggested_holding_days": 2,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-16 20:57:16",
          "trade_date": "2026-03-17",
          "symbol": "600426",
          "name": "华鲁恒升",
          "threshold_mode": "normal",
          "score_total": 70.76,
          "close": 39.21,
          "stop_loss_price": 34.7,
          "take_profit_price": 48.22,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-16 20:57:16",
          "trade_date": "2026-03-17",
          "symbol": "600582",
          "name": "天地科技",
          "threshold_mode": "normal",
          "score_total": 70.7,
          "close": 6.15,
          "stop_loss_price": 5.97,
          "take_profit_price": 6.49,
          "suggested_holding_days": 2,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-16 09:13:28",
          "trade_date": "2026-03-16",
          "symbol": "002360",
          "name": "同德化工",
          "threshold_mode": "normal",
          "score_total": 91.45,
          "close": 6.69,
          "stop_loss_price": 6.27,
          "take_profit_price": 7.52,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-16 09:13:28",
          "trade_date": "2026-03-16",
          "symbol": "603507",
          "name": "振江股份",
          "threshold_mode": "normal",
          "score_total": 89.81,
          "close": 37.57,
          "stop_loss_price": 34.73,
          "take_profit_price": 43.24,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-16 09:13:28",
          "trade_date": "2026-03-16",
          "symbol": "601877",
          "name": "正泰电器",
          "threshold_mode": "normal",
          "score_total": 89.57,
          "close": 38.33,
          "stop_loss_price": 35.38,
          "take_profit_price": 44.21,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-15 12:23:58",
          "trade_date": "2026-03-16",
          "symbol": "603519",
          "name": "立霸股份",
          "threshold_mode": "normal",
          "score_total": 70.76,
          "close": 13.74,
          "stop_loss_price": 13.21,
          "take_profit_price": 14.78,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-15 12:23:59",
          "trade_date": "2026-03-16",
          "symbol": "603856",
          "name": "东宏股份",
          "threshold_mode": "normal",
          "score_total": 70.37,
          "close": 13.99,
          "stop_loss_price": 13.12,
          "take_profit_price": 15.71,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-15 12:23:59",
          "trade_date": "2026-03-16",
          "symbol": "002929",
          "name": "润建股份",
          "threshold_mode": "normal",
          "score_total": 69.81,
          "close": 50.2,
          "stop_loss_price": 45.73,
          "take_profit_price": 59.13,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-15 11:39:06",
          "trade_date": "2026-03-13",
          "symbol": "600075",
          "name": "新疆天业",
          "threshold_mode": "normal",
          "score_total": 92.08,
          "close": 7.8,
          "stop_loss_price": 7.16,
          "take_profit_price": 9.07,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-15 11:39:06",
          "trade_date": "2026-03-13",
          "symbol": "002092",
          "name": "中泰化学",
          "threshold_mode": "normal",
          "score_total": 90.24,
          "close": 8.5,
          "stop_loss_price": 7.66,
          "take_profit_price": 10.16,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-15 11:39:06",
          "trade_date": "2026-03-13",
          "symbol": "600873",
          "name": "梅花生物",
          "threshold_mode": "normal",
          "score_total": 90.04,
          "close": 12.7,
          "stop_loss_price": 12.09,
          "take_profit_price": 13.91,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-13 15:25:40",
          "trade_date": "2026-03-13",
          "symbol": "002299",
          "name": "圣农发展",
          "threshold_mode": "normal",
          "score_total": 68.49,
          "close": 19.02,
          "stop_loss_price": 18.18,
          "take_profit_price": 20.69,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-13 15:25:40",
          "trade_date": "2026-03-13",
          "symbol": "600202",
          "name": "哈空调",
          "threshold_mode": "normal",
          "score_total": 68.15,
          "close": 6.43,
          "stop_loss_price": 6.14,
          "take_profit_price": 6.99,
          "suggested_holding_days": 2,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-13 15:25:40",
          "trade_date": "2026-03-13",
          "symbol": "002170",
          "name": "芭田股份",
          "threshold_mode": "normal",
          "score_total": 67.47,
          "close": 14.01,
          "stop_loss_price": 13.01,
          "take_profit_price": 15.99,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend-pullback"
        },
        {
          "run_time": "2026-03-11 20:12:14",
          "trade_date": "2026-03-12",
          "symbol": "002986",
          "name": "宇新股份",
          "threshold_mode": "normal",
          "score_total": 91.17,
          "close": 16.81,
          "stop_loss_price": 15.31,
          "take_profit_price": 19.81,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-11 20:12:14",
          "trade_date": "2026-03-12",
          "symbol": "000720",
          "name": "新能泰山",
          "threshold_mode": "normal",
          "score_total": 90.45,
          "close": 4.4,
          "stop_loss_price": 4.07,
          "take_profit_price": 5.05,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-11 20:12:14",
          "trade_date": "2026-03-12",
          "symbol": "002648",
          "name": "卫星化学",
          "threshold_mode": "normal",
          "score_total": 88.17,
          "close": 27.93,
          "stop_loss_price": 25.67,
          "take_profit_price": 32.43,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-10 19:15:49",
          "trade_date": "2026-03-11",
          "symbol": "000720",
          "name": "新能泰山",
          "threshold_mode": "normal",
          "score_total": 91.08,
          "close": 4.46,
          "stop_loss_price": 4.15,
          "take_profit_price": 5.06,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-10 19:15:49",
          "trade_date": "2026-03-11",
          "symbol": "002986",
          "name": "宇新股份",
          "threshold_mode": "normal",
          "score_total": 90.26,
          "close": 16.1,
          "stop_loss_price": 14.7,
          "take_profit_price": 18.88,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-10 19:15:49",
          "trade_date": "2026-03-11",
          "symbol": "600131",
          "name": "国网信通",
          "threshold_mode": "normal",
          "score_total": 88.22,
          "close": 22.57,
          "stop_loss_price": 21.05,
          "take_profit_price": 25.59,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-09 20:38:19",
          "trade_date": "2026-03-10",
          "symbol": "301388",
          "name": "欣灵电气",
          "threshold_mode": "normal",
          "score_total": 90.43,
          "close": 40.15,
          "stop_loss_price": 36.55,
          "take_profit_price": 47.34,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-09 20:38:19",
          "trade_date": "2026-03-10",
          "symbol": "301658",
          "name": "首航新能",
          "threshold_mode": "normal",
          "score_total": 89.34,
          "close": 41.0,
          "stop_loss_price": 37.33,
          "take_profit_price": 48.33,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-09 20:54:55",
          "trade_date": "2026-03-10",
          "symbol": "600513",
          "name": "联环药业",
          "threshold_mode": "normal",
          "score_total": 89.0,
          "close": 23.48,
          "stop_loss_price": 21.92,
          "take_profit_price": 26.59,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-09 20:54:55",
          "trade_date": "2026-03-10",
          "symbol": "600714",
          "name": "金瑞矿业",
          "threshold_mode": "normal",
          "score_total": 88.25,
          "close": 22.02,
          "stop_loss_price": 19.39,
          "take_profit_price": 27.27,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-09 20:54:55",
          "trade_date": "2026-03-10",
          "symbol": "600938",
          "name": "中国海油",
          "threshold_mode": "normal",
          "score_total": 87.51,
          "close": 43.36,
          "stop_loss_price": 39.9,
          "take_profit_price": 50.26,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-06 21:06:31",
          "trade_date": "2026-03-09",
          "symbol": "600236",
          "name": "桂冠电力",
          "threshold_mode": "normal",
          "score_total": 91.95,
          "close": 10.95,
          "stop_loss_price": 10.14,
          "take_profit_price": 12.55,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-06 21:06:31",
          "trade_date": "2026-03-09",
          "symbol": "600149",
          "name": "廊坊发展",
          "threshold_mode": "normal",
          "score_total": 89.16,
          "close": 7.13,
          "stop_loss_price": 6.54,
          "take_profit_price": 8.3,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-06 21:06:31",
          "trade_date": "2026-03-09",
          "symbol": "000912",
          "name": "泸天化",
          "threshold_mode": "normal",
          "score_total": 88.18,
          "close": 5.54,
          "stop_loss_price": 5.07,
          "take_profit_price": 6.47,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-06 09:13:07",
          "trade_date": "2026-03-06",
          "symbol": "603318",
          "name": "水发燃气",
          "threshold_mode": "normal",
          "score_total": 91.26,
          "close": 9.6,
          "stop_loss_price": 8.93,
          "take_profit_price": 10.93,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-06 09:13:07",
          "trade_date": "2026-03-06",
          "symbol": "600149",
          "name": "廊坊发展",
          "threshold_mode": "normal",
          "score_total": 90.77,
          "close": 6.87,
          "stop_loss_price": 6.31,
          "take_profit_price": 7.97,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-06 09:13:07",
          "trade_date": "2026-03-06",
          "symbol": "601857",
          "name": "中国石油",
          "threshold_mode": "normal",
          "score_total": 88.16,
          "close": 12.69,
          "stop_loss_price": 11.77,
          "take_profit_price": 14.52,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 00:19:03",
          "trade_date": "2026-03-05",
          "symbol": "000912",
          "name": "泸天化",
          "threshold_mode": "force",
          "score_total": 94.09,
          "close": 5.68,
          "stop_loss_price": 5.3,
          "take_profit_price": 6.42,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 00:19:03",
          "trade_date": "2026-03-05",
          "symbol": "002350",
          "name": "北京科锐",
          "threshold_mode": "force",
          "score_total": 92.87,
          "close": 13.32,
          "stop_loss_price": 12.22,
          "take_profit_price": 15.51,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 00:19:03",
          "trade_date": "2026-03-05",
          "symbol": "002980",
          "name": "华盛昌",
          "threshold_mode": "force",
          "score_total": 92.8,
          "close": 34.02,
          "stop_loss_price": 31.95,
          "take_profit_price": 38.14,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 10:16:19",
          "trade_date": "2026-03-05",
          "symbol": "600256",
          "name": "广汇能源",
          "threshold_mode": "normal",
          "score_total": 92.21,
          "close": 6.88,
          "stop_loss_price": 6.45,
          "take_profit_price": 7.73,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 10:16:19",
          "trade_date": "2026-03-05",
          "symbol": "600821",
          "name": "金开新能",
          "threshold_mode": "normal",
          "score_total": 89.07,
          "close": 7.87,
          "stop_loss_price": 7.18,
          "take_profit_price": 9.24,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 10:16:19",
          "trade_date": "2026-03-05",
          "symbol": "000035",
          "name": "中国天楹",
          "threshold_mode": "normal",
          "score_total": 88.63,
          "close": 7.57,
          "stop_loss_price": 6.96,
          "take_profit_price": 8.78,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 10:12:31",
          "trade_date": "2026-03-04",
          "symbol": "000899",
          "name": "赣能股份",
          "threshold_mode": "normal",
          "score_total": 91.66,
          "close": 13.73,
          "stop_loss_price": 12.7,
          "take_profit_price": 15.78,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-03 17:01:30",
          "trade_date": "2026-03-04",
          "symbol": "001209",
          "name": "洪兴股份",
          "threshold_mode": "normal",
          "score_total": 90.58,
          "close": 29.27,
          "stop_loss_price": 26.21,
          "take_profit_price": 35.37,
          "suggested_holding_days": 2,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-03 17:01:30",
          "trade_date": "2026-03-04",
          "symbol": "002350",
          "name": "北京科锐",
          "threshold_mode": "normal",
          "score_total": 89.41,
          "close": 11.89,
          "stop_loss_price": 11.11,
          "take_profit_price": 13.43,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 10:12:31",
          "trade_date": "2026-03-04",
          "symbol": "002470",
          "name": "金正大",
          "threshold_mode": "normal",
          "score_total": 88.93,
          "close": 2.79,
          "stop_loss_price": 2.48,
          "take_profit_price": 3.39,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-03 17:01:30",
          "trade_date": "2026-03-04",
          "symbol": "600938",
          "name": "中国海油",
          "threshold_mode": "normal",
          "score_total": 87.75,
          "close": 39.46,
          "stop_loss_price": 37.41,
          "take_profit_price": 43.55,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 10:12:31",
          "trade_date": "2026-03-04",
          "symbol": "002015",
          "name": "协鑫能科",
          "threshold_mode": "normal",
          "score_total": 87.27,
          "close": 14.13,
          "stop_loss_price": 12.96,
          "take_profit_price": 16.45,
          "suggested_holding_days": 1,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 16:52:13",
          "trade_date": "2026-03-03",
          "symbol": "001209",
          "name": "洪兴股份",
          "threshold_mode": "normal",
          "score_total": 90.58,
          "close": 29.27,
          "stop_loss_price": 26.21,
          "take_profit_price": 35.37,
          "suggested_holding_days": 2,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 16:52:13",
          "trade_date": "2026-03-03",
          "symbol": "002350",
          "name": "北京科锐",
          "threshold_mode": "normal",
          "score_total": 89.41,
          "close": 11.89,
          "stop_loss_price": 11.11,
          "take_profit_price": 13.43,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-03-05 16:52:13",
          "trade_date": "2026-03-03",
          "symbol": "600938",
          "name": "中国海油",
          "threshold_mode": "normal",
          "score_total": 87.75,
          "close": 39.46,
          "stop_loss_price": 37.41,
          "take_profit_price": 43.55,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-02-28 15:51:33",
          "trade_date": "2026-03-02",
          "symbol": "600821",
          "name": "金开新能",
          "threshold_mode": "normal",
          "score_total": 92.96,
          "close": 7.39,
          "stop_loss_price": 6.85,
          "take_profit_price": 8.47,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-02-28 15:51:33",
          "trade_date": "2026-03-02",
          "symbol": "600470",
          "name": "六国化工",
          "threshold_mode": "normal",
          "score_total": 90.26,
          "close": 7.94,
          "stop_loss_price": 7.28,
          "take_profit_price": 9.24,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-02-28 15:51:33",
          "trade_date": "2026-03-02",
          "symbol": "603002",
          "name": "宏昌电子",
          "threshold_mode": "normal",
          "score_total": 87.39,
          "close": 11.54,
          "stop_loss_price": 10.64,
          "take_profit_price": 13.32,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-02-26 18:07:32",
          "trade_date": "2026-02-27",
          "symbol": "600821",
          "name": "金开新能",
          "threshold_mode": "normal",
          "score_total": 89.61,
          "close": 6.72,
          "stop_loss_price": 6.23,
          "take_profit_price": 7.69,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-02-26 09:11:06",
          "trade_date": "2026-02-26",
          "symbol": "605007",
          "name": "五洲特纸",
          "threshold_mode": "normal",
          "score_total": 91.48,
          "close": 17.23,
          "stop_loss_price": 16.05,
          "take_profit_price": 19.57,
          "suggested_holding_days": 3,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-02-25 16:17:45",
          "trade_date": "2026-02-25",
          "symbol": "000007",
          "name": "全新好",
          "threshold_mode": "normal",
          "score_total": 71.26,
          "close": 12.7,
          "stop_loss_price": 11.9,
          "take_profit_price": 14.1,
          "suggested_holding_days": null,
          "exit_plan": "",
          "source_strategy": "recommend"
        },
        {
          "run_time": "2026-02-25 16:14:37",
          "trade_date": "2026-02-25",
          "symbol": "000001",
          "name": "平安银行",
          "threshold_mode": "normal",
          "score_total": 70.1,
          "close": 12.3,
          "stop_loss_price": 11.8,
          "take_profit_price": 13.8,
          "suggested_holding_days": null,
          "exit_plan": "",
          "source_strategy": "recommend"
        }
      ]
    }
  },
  "all_dates": [
    "2026-06-08",
    "2026-06-05",
    "2026-06-04",
    "2026-06-03",
    "2026-06-02",
    "2026-06-01",
    "2026-05-29",
    "2026-05-28",
    "2026-05-27",
    "2026-05-26",
    "2026-05-25",
    "2026-05-22",
    "2026-05-21",
    "2026-05-20",
    "2026-05-19",
    "2026-05-18",
    "2026-05-15",
    "2026-05-14",
    "2026-05-13",
    "2026-05-12",
    "2026-05-11",
    "2026-05-08",
    "2026-05-07",
    "2026-05-06",
    "2026-04-30",
    "2026-04-29",
    "2026-04-28",
    "2026-04-27",
    "2026-04-24",
    "2026-04-23",
    "2026-04-22",
    "2026-04-21",
    "2026-04-20",
    "2026-04-17",
    "2026-04-16",
    "2026-04-15",
    "2026-04-14",
    "2026-04-13",
    "2026-04-10",
    "2026-04-09",
    "2026-04-08",
    "2026-04-07",
    "2026-04-03",
    "2026-04-02",
    "2026-04-01",
    "2026-03-31",
    "2026-03-30",
    "2026-03-27",
    "2026-03-26",
    "2026-03-25",
    "2026-03-24",
    "2026-03-23",
    "2026-03-20",
    "2026-03-19",
    "2026-03-18",
    "2026-03-17",
    "2026-03-16",
    "2026-03-13",
    "2026-03-12",
    "2026-03-11",
    "2026-03-10",
    "2026-03-09",
    "2026-03-06",
    "2026-03-05",
    "2026-03-04",
    "2026-03-03",
    "2026-03-02",
    "2026-02-27",
    "2026-02-26",
    "2026-02-25"
  ]
};
